name: Clang Format

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  clang-format:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Check formatting in linter/
        run: nix develop --command bash scripts/check-format.sh
